---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metrics-demo
  annotations:
    cert-manager.io/cluster-issuer: zasda-test-ca
spec:
  tls:
    - hosts:
        - metrics-demo.zasda.test
      secretName: metrics-demo-zasda-test
  rules:
    - host: metrics-demo.zasda.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metrics-demo
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-demo
  labels:
    prometheus-instance: default
spec:
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: metrics-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-demo
  template:
    spec:
      containers:
        - image: luxas/autoscale-demo:v0.1.2
          name: metrics-provider
          ports:
            - containerPort: 8080
              name: metrics
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  name: metrics-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metricName: http_requests
        targetAverageValue: 1
