version: "3"

services:
  darkhttpd:
    image: p3terx/darkhttpd:1.14
    command:
      - /var/www/htdocs
      - --port
      - "8083"
    volumes:
      - /srv/www/file:/var/www/htdocs:ro
    logging:
      driver: local
    network_mode: host
