metrics_address: 127.0.0.1:9090

authenticate_service_url: https://authenticate.pomerium.app

routes:
- from: https://grafana.zasdaym.my.id
  to: http://localhost:3000
  policy:
  - allow:
      or:
      - email:
          is: zasdaym@gmail.com

- from: https://logs.zasdaym.my.id
  to: http://localhost:9428
  policy:
  - allow:
      or:
      - email:
          is: zasdaym@gmail.com

- from: https://pph21.zasdaym.my.id
  to: http://localhost:3001
  allow_public_unauthenticated_access: true
