#cloud-config
groups:
  - docker

users:
  - default
  - name: zasda
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:zasdaym
    groups: docker

package_update: true
package_upgrade: true
packages:
  - docker.io
