argo-cd:
  configs:
    cm:
      url: https://argo-cd.zasdaym.my.id
    params:
      server.disable.auth: true
      server.insecure: true
  server:
    ingress:
      annotations:
        kubernetes.io/ingress.class: istio
      enabled: true
      hosts:
        - argo-cd.zasdaym.my.id
