---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  gateways:
    - argo-cd
  hosts:
    - argo-cd.zasda.test
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: z-cluster-0-argo-cd-argocd-server
            port:
              number: 80
