authenticate_service_url: https://authenticate.pomerium.app

jwt_claims_headers:
  X-Email: email

routes:
  - from: https://argo-cd.zasdaym.my.id
    to: http://172.18.0.2:31292
    policy:
      - allow:
          or:
            - email:
                is: zasdaym@gmail.com

  - from: https://dns.zasdaym.my.id
    to: http://localhost:8053
    allow_public_unauthenticated_access: true

  - from: https://echo.zasdaym.my.id
    to: http://localhost:8080
    allow_public_unauthenticated_access: true

  - from: https://file.zasdaym.my.id
    to: http://localhost:8083
    allow_public_unauthenticated_access: true

  - from: https://grafana.zasdaym.my.id
    to: http://localhost:3000
    policy:
      - allow:
          or:
            - email:
                is: zasdaym@gmail.com
    pass_identity_headers: true

  - from: https://kms.zasdaym.my.id
    to: https://massgrave.dev/get.ps1
    allow_public_unauthenticated_access: true

  - from: https://tsnr.zasdaym.my.id
    to: http://localhost:8081
    allow_public_unauthenticated_access: true

  - from: https://wiki.zasdaym.my.id
    to: http://localhost:8082
    policy:
      - allow:
          or:
            - email:
                is: zasdaym@gmail.com
