[sources.docker]
type = "docker_logs"

[sinks.victorialogs]
type = "elasticsearch"
inputs = [ "docker" ]
endpoints = [ "http://127.0.0.1:9428/insert/elasticsearch/" ]
mode = "bulk"
api_version = "v8"
healthcheck.enabled = false

[sinks.victorialogs.query]
_msg_field = "message"
_time_field = "timestamp"
_stream_fields = "host,container_name"

[sources.vector_metrics]
type = "internal_metrics"

[sinks.victoriametrics]
type = "prometheus_remote_write"
endpoint = "http://127.0.0.1:8428/api/v1/write"
inputs = [ "vector_metrics" ]
healthcheck.enabled = false
