---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  annotations:
    cert-manager.io/cluster-issuer: zasda-test-ca
spec:
  tls:
    - hosts:
        - prometheus.zasda.test
      secretName: prometheus-zasda-test
  rules:
    - host: prometheus.zasda.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default
                port:
                  number: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: default
spec:
  serviceMonitorSelector:
    matchLabels:
      prometheus-instance: default
  replicas: 1
  resources:
    requests:
      memory: 512Mi
  serviceAccountName: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
  labels:
    prometheus-instance: default
spec:
  namespaceSelector:
    any: true
  selector:
      matchLabels:
        prometheus-instance: default
  endpoints:
    - port: metrics
      path: /metrics
