---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: default
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      scrape: "true"
  resources:
    requests:
      memory: 512Mi
  enableAdminAPI: false
