---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  annotations:
    cert-manager.io/cluster-issuer: zasda-test-ca
spec:
  tls:
    - hosts:
        - prometheus.zasda.test
      secretName: prometheus-zasda-test
  defaultBackend:
    service:
      name: default
      port:
        number: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    prometheus: default
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: default
spec:
  podMonitorSelector:
    matchLabels:
      scrape: "true"
  replicas: 1
  resources:
    requests:
      memory: 512Mi
  serviceAccountName: prometheus
