scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - localhost:8080
  - job_name: haproxy
    static_configs:
      - targets:
          - localhost:8404
  - job_name: node_exporter
    static_configs:
      - targets:
          - localhost:9100
