apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: github-zasdaym-infra
spec:
  generators:
    - git:
        repoURL: https://github.com/zasdaym/infra.git
        revision: HEAD
        directories:
          - kubernetes/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/zasdaym/infra.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
