apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
spec:
  template:
    spec:
      containers:
        - args:
            - --update-status
          command:
            - controller
          name: sealed-secrets-controller
