apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: sealed-secrets-controller
          args:
            - --update-status
          env:
            - name: SEALED_SECRETS_UPDATE_STATUS
              value: "1"
