namespace: kubeseal
resources:
  - ./namespace.yaml
  - ./sealed-secret.yaml
patchesJson6902:
  - path: ./deployment-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: sealed-secrets-controller
      version: v1
