version: "3"

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana-oss:10.1.4
    environment:
      GF_SERVER_ROOT_URL: https://grafana.zasdaym.my.id
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana
    logging:
      driver: local
    network_mode: host
