version: "3"

services:
  nginx:
    image: nginx:1.24.0
    volumes:
      - /srv/www/file:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
      driver: local
    network_mode: host
