- name: General configuration
  become: yes
  gather_facts: no
  hosts: all

  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Jakarta

    - name: Install standard packages
      package:
        name:
          - aria2
          - btop
          - curl
          - dnsutils
          - tcptraceroute
          - vim

    - name: Install tailscale
      shell:
        cmd: curl -sL https://tailscale.com/install.sh | bash
        creates: /usr/bin/tailscale

    - name: Install docker
      shell:
        cmd: curl -sL https://get.docker.com | bash
        creates: /usr/bin/dockerd

    - name: Configure docker
      copy:
        src: docker/daemon.json
        dest: /etc/docker/daemon.json
      notify:
        - Restart docker

  handlers:
    - name: Restart docker
      systemd:
        name: docker
        state: restarted
