- name: General configuration
  become: true
  gather_facts: true
  hosts: all

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: Asia/Jakarta

    - name: Install standard packages
      ansible.builtin.apt:
        name:
          - aria2
          - btop
          - curl
          - dnsutils
          - tcptraceroute
          - vim

    - name: Download tailscale installer
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale_install.sh
        mode: "0644"

    - name: Run tailscale installer
      ansible.builtin.script:
        cmd: /tmp/tailscale_install.sh
        creates: /usr/bin/tailscale

    - name: Download docker installer
      ansible.builtin.get_url:
        url: https://get.docker.com
        dest: /tmp/docker_install.sh
        mode: "0644"

    - name: Run docker installer
      ansible.builtin.script:
        cmd: /tmp/docker_install.sh
        creates: /usr/bin/dockerd

    - name: Configure docker
      ansible.builtin.copy:
        src: docker/daemon.json
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify:
        - Restart docker

    - name: Sync blocky config
      ansible.posix.synchronize:
        src: files/blocky/
        dest: /home/zasda/blocky/
      notify:
        - Start blocky

    - name: Sync darkhttpd config
      ansible.posix.synchronize:
        src: files/darkhttpd/
        dest: /home/zasda/darkhttpd/
      notify:
        - Start darkhttpd

    - name: Sync echo config
      ansible.posix.synchronize:
        src: files/echo/
        dest: /home/zasda/echo/
      notify:
        - Start echo

    - name: Sync grafana config
      ansible.posix.synchronize:
        src: files/grafana/
        dest: /home/zasda/grafana/
      notify:
        - Start grafana

    - name: Sync pomerium config
      ansible.posix.synchronize:
        src: files/pomerium/
        dest: /home/zasda/pomerium/
      notify:
        - Start pomerium

  handlers:
    - name: Restart docker
      ansible.builtin.systemd:
        name: docker
        state: restarted

    - name: Start blocky
      ansible.builtin.shell:
        cmd: docker compose up --detach --force-recreate --remove-orphans
        chdir: /home/zasda/blocky

    - name: Start darkhttpd
      ansible.builtin.shell:
        cmd: docker compose up --detach --force-recreate --remove-orphans
        chdir: /home/zasda/darkhttpd

    - name: Start echo
      ansible.builtin.shell:
        cmd: docker compose up --detach --force-recreate --remove-orphans
        chdir: /home/zasda/echo

    - name: Start grafana
      ansible.builtin.shell:
        cmd: docker compose up --detach --force-recreate --remove-orphans
        chdir: /home/zasda/grafana

    - name: Start pomerium
      ansible.builtin.shell:
        cmd: docker compose up --detach --force-recreate --remove-orphans
        chdir: /home/zasda/pomerium
