- name: General configuration
  become: yes
  gather_facts: no
  hosts: all

  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Jakarta

    - name: Install standard packages
      package:
        name:
          - aria2
          - btop
          - curl
          - dnsutils
          - tcptraceroute
          - vim

    - name: Install tailscale
      shell:
        cmd: curl -sL https://tailscale.com/install.sh | bash
        creates: /usr/bin/tailscale

    - name: Install docker
      shell:
        cmd: curl -sL https://get.docker.com | bash
        creates: /usr/bin/dockerd

    - name: Configure docker
      copy:
        src: docker/daemon.json
        dest: /etc/docker/daemon.json
      notify:
        - Restart docker

    - name: Sync compose directory
      synchronize:
        src: compose/
        dest: /home/zasda/compose/
      notify:
        - Restart caddy

    - name: Copy nomad configuration
      copy:
        src: nomad.d/nomad.hcl
        dest: /etc/nomad.d/nomad.hcl

  handlers:
    - name: Restart docker
      systemd:
        name: docker
        state: restarted

    - name: Compose up
      shell:
        cmd: cd /home/zasda/compose && docker compose up -d --remove-orphans

    - name: Restart caddy
      shell:
        cmd: cd /home/zasda/compose && docker compose restart caddy
