- name: General configuration
  become: yes
  gather_facts: no
  hosts: all

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: Asia/Jakarta

    - name: Install standard packages
      ansible.builtin.package:
        name:
          - aria2
          - btop
          - curl
          - dnsutils
          - tcptraceroute
          - vim

    - name: Install tailscale
      ansible.builtin.shell:
        cmd: curl -sL https://tailscale.com/install.sh | bash
        creates: /usr/bin/tailscale
