---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - argocd.zasda.test
      port:
        name: http
        number: 80
        protocol: HTTP
