base:
  '*':
    - basic
    - docker
    - beyla
    - coroot.absent
    - cadvisor
    - grafana
    - haproxy.absent
    - hashicorp
    - ladder.absent
    - nginx
    - node_exporter
    - pomerium.absent
    - postgresql
    - pph21
    - privoxy.absent
    - umami
    - vector
    - victorialogs
    - victoriametrics
