---
- name: Deploy nomad jobs
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Copy nomad job files
      ansible.builtin.copy:
        src: ../nomad/
        dest: /srv/nomad/

    - name: Sync nomad jobs
      ansible.builtin.script:
        cmd: ../scripts/sync.sh
