version: "3"

x-service-default: &x-service-default
  logging:
    driver: local
  network_mode: host

volumes:
  grafana_data: {}
  postgres_data: {}

services:
  blocky:
    <<: *x-service-default
    image: spx01/blocky:v0.22
    volumes:
      - ./blocky/config.yml:/app/config.yml:ro

  darkhttpd:
    <<: *x-service-default
    image: p3terx/darkhttpd:1.14
    command:
      - /var/www/htdocs
      - --port
      - "8083"
    volumes:
      - /srv/www/file:/var/www/htdocs:ro

  dragonfly:
    <<: *x-service-default
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0
    ulimits:
      memlock: "-1"

  echo:
    <<: *x-service-default
    image: mendhak/http-https-echo:30
    environment:
      HTTP_PORT: "8080"

  grafana:
    <<: *x-service-default
    image: grafana/grafana-oss:10.1.4
    environment:
      GF_SERVER_ROOT_URL: https://grafana.zasdaym.my.id
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - grafana_data:/var/lib/grafana

  pomerium:
    <<: *x-service-default
    image: pomerium/pomerium:0-23-0
    volumes:
      - ./pomerium/config.yaml:/pomerium/config.yaml:ro

  postgres:
    <<: *x-service-default
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgres
