version: '3'

x-service-default: &x-service-default
  logging:
    driver: local
  network_mode: host

volumes:
  caddy_config: {}
  caddy_data: {}
  postgres_data: {}

services:
  caddy:
    <<: *x-service-default
    image: caddy:2.7.4
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data

  dragonfly:
    <<: *x-service-default
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.8.0
    ulimits:
      memlock: "-1"

  echo:
    <<: *x-service-default
    image: mendhak/http-https-echo:30
    environment:
      HTTP_PORT: "8080"

  postgres:
    <<: *x-service-default
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgres
