version: "3"

volumes:
  postgres_data: {}
  storage_data: {}

services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline
    env_file:
      - .env
    environment:
      NODE_ENV: production
      URL: https://wiki.zasdaym.my.id
      FILE_STORAGE: s3
      AWS_S3_UPLOAD_BUCKET_URL: http://storage:9000
      AWS_S3_FORCE_PATH_STYLE: "true"
      AWS_S3_ACL: private
      PGSSLMODE: disable
      REDIS_URL: redis://redis:6379
    ports:
      - 127.0.0.1:8082:3000
    logging:
      driver: local

  redis:
    image: redis:7.2.1
    logging:
      driver: local

  postgres:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgres/data
    logging:
      driver: local

  storage:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    volumes:
      - storage_data:/data
    logging:
      driver: local
