apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: zasdaym-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/zasdaym/gitops.git
        revision: HEAD
        files:
        - path: 'apps/**/config.json'
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/zasdaym/gitops.git
        targetRevision: HEAD
        path: 'apps/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      ignoreDifference: '{{ignoreDifference}}'
