apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: zasda-test-ca
spec:
  tls:
    - hosts:
        - argocd.zasda.test
      secretName: argocd-zasda-test
  rules:
    - host: argocd.zasda.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
