apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
spec:
  rules:
    - host: argocd.zasda.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
            service:
              name: argocd-server
              port:
                number: 80
