namespace: argocd
resources:
  - namespace.yaml
  - install.yaml
  - applicationset-install.yaml
  - applicationset.yaml
patches:
  - path: resources-requests-patch.yaml
    target:
      kind: Deployment
  - path: resources-requests-patch.yaml
    target:
      kind: StatefulSet
